### PR TITLE
genregions

### PR DESCRIPTION
**Pull request by sshipway**
Documentation for 
-- genregions subcommand
-- using with Minecraft 1.7
-- how to pregenerate terrain

### CODE REVIEW

**Comment by sshipway** [comment]
Documentation for the new `--genregions` subcommand.

In addition, a couple of other FAQ items that I've had here for a while but never submitted.

**Comment by JoeFowlerJDi** [comment]
The last FAQs seems to be cut-off half way through. I can see the rest of it in the source, however. Is this a formatting error?

**Comment by JiFish** [comment]
The last FAQs seems to be cut-off half way through. I can see the rest of it in the source, however. Is this a formatting error?

**Comment by sshipway** [comment]
A misunderstanding on my part on how to use the Sphinx formatting language.  Corrected now, I think.

**Pull request merged**
